version: '3'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: snippetbox
      POSTGRES_USER: snippetbox
      POSTGRES_PASSWORD: snippetbox
    volumes:
      - ./pgdata:/var/lib/postgresql/data